# Symlink to this file from ~/.zshrc
# You should also symlink ~/.zshenv to zsh/env in this directory

. ~/bin/dotfiles/zsh/config
. ~/bin/dotfiles/zsh/aliases



PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
